import React from 'react';
import { Link } from 'react-router-dom';

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-gray-900 text-white flex flex-col font-sans">
      {/* Navigation */}
      <nav className="flex items-center justify-between p-6 max-w-7xl mx-auto w-full">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-green-500 rounded-lg flex items-center justify-center font-bold text-gray-900">
            EL
          </div>
          <span className="text-xl font-bold tracking-wider text-green-400">ExpenseLens</span>
        </div>
        <div className="flex items-center gap-4">
          <Link to="/login" className="text-gray-300 hover:text-white transition">Login</Link>
          <Link to="/signup" className="bg-green-500 hover:bg-green-400 text-gray-900 font-medium px-4 py-2 rounded transition">
            Sign Up
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <main className="flex-1 flex flex-col items-center justify-center text-center px-6 max-w-4xl mx-auto mt-12 mb-24">
        <div className="inline-block mb-4 px-3 py-1 rounded-full bg-blue-900/30 border border-blue-500/30 text-blue-400 text-sm font-medium tracking-wide">
          Introducing AI Financial Advice
        </div>
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6 leading-tight">
          See your money <span className="text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-blue-500">clearly</span>.
        </h1>
        <p className="text-xl text-gray-400 mb-10 max-w-2xl leading-relaxed">
          Upload your bank statements. Let AI automatically categorize your transactions, track your budget, and give you personalized advice to help you save more.
        </p>
        <div className="flex flex-col sm:flex-row gap-4">
          <Link to="/signup" className="bg-green-500 hover:bg-green-400 text-gray-900 text-lg font-bold px-8 py-4 rounded-xl shadow-lg shadow-green-500/20 transition hover:-translate-y-1">
            Get Started for Free
          </Link>
          <a href="#features" className="bg-gray-800 hover:bg-gray-700 text-white text-lg font-medium px-8 py-4 rounded-xl border border-gray-700 transition">
            Learn More
          </a>
        </div>
      </main>

      {/* Features Grid */}
      <section id="features" className="bg-gray-800 py-24">
        <div className="max-w-7xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center mb-16">Everything you need to master your finances</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
            
            {/* Feature 1 */}
            <div className="flex flex-col items-center text-center">
              <div className="w-16 h-16 bg-blue-900/50 rounded-2xl flex items-center justify-center mb-6 text-2xl border border-blue-500/20">
                📄
              </div>
              <h3 className="text-xl font-bold mb-3">Auto-Categorization</h3>
              <p className="text-gray-400 leading-relaxed">
                Upload a PDF bank statement and our intelligent parser accurately extracts and maps your transactions to your custom categories.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="flex flex-col items-center text-center">
              <div className="w-16 h-16 bg-green-900/50 rounded-2xl flex items-center justify-center mb-6 text-2xl border border-green-500/20">
                📊
              </div>
              <h3 className="text-xl font-bold mb-3">Smart Budgeting</h3>
              <p className="text-gray-400 leading-relaxed">
                Set baseline percentages. Let ExpenseLens auto-balance your budget and handle month-to-month rollovers automatically.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="flex flex-col items-center text-center">
              <div className="w-16 h-16 bg-purple-900/50 rounded-2xl flex items-center justify-center mb-6 text-2xl border border-purple-500/20">
                🤖
              </div>
              <h3 className="text-xl font-bold mb-3">AI Financial Advice</h3>
              <p className="text-gray-400 leading-relaxed">
                Overspent on dining out? Get specific, actionable tips generated by Google Gemini to help you cut back next month.
              </p>
            </div>

          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 py-8 text-center text-gray-500 border-t border-gray-800">
        <p>&copy; {new Date().getFullYear()} ExpenseLens. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default LandingPage;
